export * from "./UsuarioDTO.js";
export * from "./BaseDTO.js";
export * from "./CursoDTO.js";
export * from "./SerieDTO.js";
export * from "./AlunoDTO.js";
export * from "./ProfessorDTO.js";
export * from "./CategoriaDTO.js";
export * from "./MenuDTO.js";
export * from "./UsuarioAlunoDTO.js";
