openapi: 3.0.0

info:
  title: Profet
  version: 1.0.0
  description: API Node.js

servers:
  - url: http://localhost:3000

paths:
  /auth:
    $ref: "./paths/auth.yaml"
  /usuarios:
    $ref: "./paths/usuarios/collection.yaml"
  /usuarios/{id}:
    $ref: "./paths/usuarios/item.yaml"

components:
  responses:
    "400Validacao":
      $ref: "./components/responses/400_validacao.yaml"
    "404NotFound":
      $ref: "./components/responses/404_not_found.yaml"
  schemas:
    Usuario:
      $ref: "./components/schemas/usuario/usuario.yaml"
