openapi: 3.0.0

info:
  title: Profet API
  version: 1.0.0
  description: API Node.js

servers:
  - url: http://localhost:3000

paths:
  /auth/login:
    $ref: "./paths/auth.yaml"
  /cursos:
    $ref: "./paths/cursos/index.yaml"
  /estados:
    $ref: "./paths/estados/index.yaml"
  /menus:
    $ref: "./paths/menus/index.yaml"
  /notificacoes/{id}:
    $ref: "./paths/notificacoes/_id/index.yaml"
  /projetos:
    $ref: "./paths/projetos/index.yaml"
  /projetos/{id}:
    $ref: "./paths/projetos/_id/index.yaml"
  /series:
    $ref: "./paths/series/index.yaml"
  /solicitacoes:
    $ref: "./paths/solicitacoes/index.yaml"
  /solicitacoes/{id}:
    $ref: "./paths/solicitacoes/_id/index.yaml"
  /usuarios:
    $ref: "./paths/usuarios/index.yaml"
  /usuarios/{id}:
    $ref: "./paths/usuarios/_id/index.yaml"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    "204NoContent":
      $ref: "./components/responses/204_no_content.yaml"
    "400Validacao":
      $ref: "./components/responses/400_validacao.yaml"
    "401UsuarioSemAutorizacao":
      $ref: "./components/responses/401_usuario_sem_autorizacao.yaml"
    "404NotFound":
      $ref: "./components/responses/404_not_found.yaml"
  schemas:
    Curso:
      $ref: "./components/schemas/curso/item.yaml"
    Estado:
      $ref: "./components/schemas/estado/item.yaml"
    Menu:
      $ref: "./components/schemas/menu/item.yaml"
    Notificacao:
      $ref: "./components/schemas/notificacao/item.yaml"
    Serie:
      $ref: "./components/schemas/serie/item.yaml"
    Projeto:
      $ref: "./components/schemas/projeto/item.yaml"
    ProjetoCompleto:
      $ref: "./components/schemas/projeto-completo/item.yaml"
    Solicitacao:
      $ref: "./components/schemas/solicitacao/item.yaml"
    Usuario:
      $ref: "./components/schemas/usuario/item.yaml"
    UsuarioCreate:
      type: object
      oneOf:
        - $ref: "#/components/schemas/UsuarioCreateAluno"
        - $ref: "#/components/schemas/UsuarioCreateProfessor"
      discriminator:
        propertyName: tipo
        mapping:
          aluno: "#/components/schemas/UsuarioCreateAluno"
          professor: "#/components/schemas/UsuarioCreateProfessor"
    UsuarioGet:
      type: object
      oneOf:
        - $ref: "#/components/schemas/UsuarioGetAluno"
        - $ref: "#/components/schemas/UsuarioGetProfessor"
      discriminator:
        propertyName: tipo
        mapping:
          aluno: "#/components/schemas/UsuarioGetAluno"
          professor: "#/components/schemas/UsuarioGetProfessor"
    UsuarioCreateAluno:
      $ref: "./components/schemas/usuario/create-aluno.yaml"
    UsuarioCreateProfessor:
      $ref: "./components/schemas/usuario/create-professor.yaml"
    UsuarioGetAluno:
      $ref: "./components/schemas/usuario/get-aluno.yaml"
    UsuarioGetProfessor:
      $ref: "./components/schemas/usuario/get-professor.yaml"
